//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JumpsellerSync.BusinessLogic.Provider.Nexsys.Services
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.soap.nexsys.com/")]
    public partial class ServiceException
    {
        
        private string exceptionDescriptionField;
        
        private string exceptionNameField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string exceptionDescription
        {
            get
            {
                return this.exceptionDescriptionField;
            }
            set
            {
                this.exceptionDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string exceptionName
        {
            get
            {
                return this.exceptionNameField;
            }
            set
            {
                this.exceptionNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.soap.nexsys.com/")]
    public partial class storeProduct
    {
        
        private string categoryField;
        
        private long catentryField;
        
        private bool catentryFieldSpecified;
        
        private string currencyField;
        
        private string imageField;
        
        private string inventoryField;
        
        private string long_descriptionField;
        
        private string markField;
        
        private long parentField;
        
        private bool parentFieldSpecified;
        
        private decimal priceField;
        
        private bool priceFieldSpecified;
        
        private string short_descriptionField;
        
        private string skuField;
        
        private string tax_excludedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long catentry
        {
            get
            {
                return this.catentryField;
            }
            set
            {
                this.catentryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool catentrySpecified
        {
            get
            {
                return this.catentryFieldSpecified;
            }
            set
            {
                this.catentryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string currency
        {
            get
            {
                return this.currencyField;
            }
            set
            {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string image
        {
            get
            {
                return this.imageField;
            }
            set
            {
                this.imageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string inventory
        {
            get
            {
                return this.inventoryField;
            }
            set
            {
                this.inventoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string long_description
        {
            get
            {
                return this.long_descriptionField;
            }
            set
            {
                this.long_descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string mark
        {
            get
            {
                return this.markField;
            }
            set
            {
                this.markField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public long parent
        {
            get
            {
                return this.parentField;
            }
            set
            {
                this.parentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool parentSpecified
        {
            get
            {
                return this.parentFieldSpecified;
            }
            set
            {
                this.parentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public decimal price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool priceSpecified
        {
            get
            {
                return this.priceFieldSpecified;
            }
            set
            {
                this.priceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string short_description
        {
            get
            {
                return this.short_descriptionField;
            }
            set
            {
                this.short_descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string sku
        {
            get
            {
                return this.skuField;
            }
            set
            {
                this.skuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string tax_excluded
        {
            get
            {
                return this.tax_excludedField;
            }
            set
            {
                this.tax_excludedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.soap.nexsys.com/")]
    public partial class webServiceClient
    {
        
        private string countryField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.soap.nexsys.com/", ConfigurationName="JumpsellerSync.BusinessLogic.Provider.Nexsys.Services.NexsysServiceSoap")]
    public interface NexsysServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.soap.nexsys.com/NexsysServiceSoap/StoreProductBySKURequest", ReplyAction="http://service.soap.nexsys.com/NexsysServiceSoap/StoreProductBySKUResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(JumpsellerSync.BusinessLogic.Provider.Nexsys.Services.ServiceException), Action="http://service.soap.nexsys.com/NexsysServiceSoap/StoreProductBySKU/Fault/ServiceE" +
            "xception", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<JumpsellerSync.BusinessLogic.Provider.Nexsys.Services.StoreProductBySKUResponse> StoreProductBySKUAsync(JumpsellerSync.BusinessLogic.Provider.Nexsys.Services.StoreProductBySKURequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.soap.nexsys.com/NexsysServiceSoap/StoreProductByMarksRequest", ReplyAction="http://service.soap.nexsys.com/NexsysServiceSoap/StoreProductByMarksResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(JumpsellerSync.BusinessLogic.Provider.Nexsys.Services.ServiceException), Action="http://service.soap.nexsys.com/NexsysServiceSoap/StoreProductByMarks/Fault/Servic" +
            "eException", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<JumpsellerSync.BusinessLogic.Provider.Nexsys.Services.StoreProductByMarksResponse> StoreProductByMarksAsync(JumpsellerSync.BusinessLogic.Provider.Nexsys.Services.StoreProductByMarksRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StoreProductBySKU", WrapperNamespace="http://service.soap.nexsys.com/", IsWrapped=true)]
    public partial class StoreProductBySKURequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.soap.nexsys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SKU;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.soap.nexsys.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public JumpsellerSync.BusinessLogic.Provider.Nexsys.Services.webServiceClient WSClient;
        
        public StoreProductBySKURequest()
        {
        }
        
        public StoreProductBySKURequest(string SKU, JumpsellerSync.BusinessLogic.Provider.Nexsys.Services.webServiceClient WSClient)
        {
            this.SKU = SKU;
            this.WSClient = WSClient;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StoreProductBySKUResponse", WrapperNamespace="http://service.soap.nexsys.com/", IsWrapped=true)]
    public partial class StoreProductBySKUResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.soap.nexsys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public JumpsellerSync.BusinessLogic.Provider.Nexsys.Services.storeProduct @return;
        
        public StoreProductBySKUResponse()
        {
        }
        
        public StoreProductBySKUResponse(JumpsellerSync.BusinessLogic.Provider.Nexsys.Services.storeProduct @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StoreProductByMarks", WrapperNamespace="http://service.soap.nexsys.com/", IsWrapped=true)]
    public partial class StoreProductByMarksRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.soap.nexsys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Marks", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] Marks;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.soap.nexsys.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public JumpsellerSync.BusinessLogic.Provider.Nexsys.Services.webServiceClient WSClient;
        
        public StoreProductByMarksRequest()
        {
        }
        
        public StoreProductByMarksRequest(string[] Marks, JumpsellerSync.BusinessLogic.Provider.Nexsys.Services.webServiceClient WSClient)
        {
            this.Marks = Marks;
            this.WSClient = WSClient;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="StoreProductByMarksResponse", WrapperNamespace="http://service.soap.nexsys.com/", IsWrapped=true)]
    public partial class StoreProductByMarksResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.soap.nexsys.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public JumpsellerSync.BusinessLogic.Provider.Nexsys.Services.storeProduct[] @return;
        
        public StoreProductByMarksResponse()
        {
        }
        
        public StoreProductByMarksResponse(JumpsellerSync.BusinessLogic.Provider.Nexsys.Services.storeProduct[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface NexsysServiceSoapChannel : JumpsellerSync.BusinessLogic.Provider.Nexsys.Services.NexsysServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class NexsysServiceSoapClient : System.ServiceModel.ClientBase<JumpsellerSync.BusinessLogic.Provider.Nexsys.Services.NexsysServiceSoap>, JumpsellerSync.BusinessLogic.Provider.Nexsys.Services.NexsysServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public NexsysServiceSoapClient() : 
                base(NexsysServiceSoapClient.GetDefaultBinding(), NexsysServiceSoapClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.NexsysServiceSoapPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NexsysServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(NexsysServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), NexsysServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NexsysServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(NexsysServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NexsysServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(NexsysServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NexsysServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JumpsellerSync.BusinessLogic.Provider.Nexsys.Services.StoreProductBySKUResponse> JumpsellerSync.BusinessLogic.Provider.Nexsys.Services.NexsysServiceSoap.StoreProductBySKUAsync(JumpsellerSync.BusinessLogic.Provider.Nexsys.Services.StoreProductBySKURequest request)
        {
            return base.Channel.StoreProductBySKUAsync(request);
        }
        
        public System.Threading.Tasks.Task<JumpsellerSync.BusinessLogic.Provider.Nexsys.Services.StoreProductBySKUResponse> StoreProductBySKUAsync(string SKU, JumpsellerSync.BusinessLogic.Provider.Nexsys.Services.webServiceClient WSClient)
        {
            JumpsellerSync.BusinessLogic.Provider.Nexsys.Services.StoreProductBySKURequest inValue = new JumpsellerSync.BusinessLogic.Provider.Nexsys.Services.StoreProductBySKURequest();
            inValue.SKU = SKU;
            inValue.WSClient = WSClient;
            return ((JumpsellerSync.BusinessLogic.Provider.Nexsys.Services.NexsysServiceSoap)(this)).StoreProductBySKUAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<JumpsellerSync.BusinessLogic.Provider.Nexsys.Services.StoreProductByMarksResponse> JumpsellerSync.BusinessLogic.Provider.Nexsys.Services.NexsysServiceSoap.StoreProductByMarksAsync(JumpsellerSync.BusinessLogic.Provider.Nexsys.Services.StoreProductByMarksRequest request)
        {
            return base.Channel.StoreProductByMarksAsync(request);
        }
        
        public System.Threading.Tasks.Task<JumpsellerSync.BusinessLogic.Provider.Nexsys.Services.StoreProductByMarksResponse> StoreProductByMarksAsync(string[] Marks, JumpsellerSync.BusinessLogic.Provider.Nexsys.Services.webServiceClient WSClient)
        {
            JumpsellerSync.BusinessLogic.Provider.Nexsys.Services.StoreProductByMarksRequest inValue = new JumpsellerSync.BusinessLogic.Provider.Nexsys.Services.StoreProductByMarksRequest();
            inValue.Marks = Marks;
            inValue.WSClient = WSClient;
            return ((JumpsellerSync.BusinessLogic.Provider.Nexsys.Services.NexsysServiceSoap)(this)).StoreProductByMarksAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NexsysServiceSoapPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NexsysServiceSoapPort))
            {
                return new System.ServiceModel.EndpointAddress("https://app.nexsysla.com/nexsysServiceSoap/NexsysServiceSoap");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return NexsysServiceSoapClient.GetBindingForEndpoint(EndpointConfiguration.NexsysServiceSoapPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return NexsysServiceSoapClient.GetEndpointAddress(EndpointConfiguration.NexsysServiceSoapPort);
        }
        
        public enum EndpointConfiguration
        {
            
            NexsysServiceSoapPort,
        }
    }
}
